### PR TITLE
Complete mapping reference

### PR DESCRIPTION
**Pull request by guiwoda**
Huge file, with the index on top.

Haven't tested internal links, but they should work! :smile:

### CODE REVIEW

**Comment by guiwoda** [comment]
Ugh, _don't merge this yet_!

I thought code on headers would look fine, but it doesn't.

**Comment by guiwoda** [comment]
Now it's mergeable! :smile:

**Comment by guiwoda** [comment]
Related to #22 #23 #24 #25 and #26

**Comment by FoxxMD** [comment]
Wow awesome work @guiwoda ! :+1:

**Comment by guiwoda** [comment]
Thank you @FoxxMD :smile:

**Pull request merged**
