### PR TITLE
Added documentation about Mapping types

### PR DESCRIPTION
**Pull request by josenicomaia**
Added documentation about Mapping types

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
@josenicomaia can you resolve the merge conflicts? Thanks

**Comment by josenicomaia** [comment]
Sure ;D

**Comment by josenicomaia** [comment]
Done

**Comment by josenicomaia** [comment]
PS: I sent an PM about https://github.com/laravel-doctrine/orm/pull/111

Thanks

**Comment by josenicomaia** [comment]
@patrickbrouwers Is it mergeable?

**Pull request merged**
